featured_categories:
  type: objects
  default: []
  schema:
    name: carte
    properties:
      category:
        type: categories
        required: true
        validations:
          min: 1
          max: 1
      title:
        type: string
        required: false
        validations:
          max_length: 60
      description:
        type: string
        required: false
        validations:
          max_length: 160
      icon:
        type: icon
        required: false

show_hot_topics:
  type: bool
  default: true

hot_topics_count:
  type: integer
  default: 5
  min: 1
  max: 10
